# Site
name: "Andrimo"
description: "All About Android."
meta_description: "All About Android, we provide free android help and latest android tricks, tips, latest smartphone, gadgets review and more.."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-135019824-1'
disqus: 'andrimo'
mailchimp-list: 'https://eepurl.com/gg6EE5'
include: ["_pages"]
permalink: /:title/
site.url: 'https://'

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
